### ISSUE TITLE
Fix a new bug by...

### ISSUE THREAD

**Issue by Abbaskhurram255** [Abbaskhurram255/abbaskhurram255.github.io#5]
Fix a new bug by replacing this code with the old one to run speech synthesis even when user presses enter key instead of just clicking the Ask button):

$('#searchInput').keydown(function(e) {
    const code = e.keyCode ? e.keyCode : e.which;
    if (code == 13) {
      ask();
      if (mesg.innerText != '') {
  if (speechSynthesis.speaking) {
  stopText();
  }
 playText(mesg.innerText);
 //Show a snackbar each time Speech Synthesis reads the text
 snack.innerText = "Speech synthesis is ongoing. You can't enter text in the input field until it finishes reading.";
        snack.className = 'show';
        /*optional expression*/
        setTimeout(function(){
          snack.className = snack.className.replace("show", ""); }, 4000);
         }
    }
 });

**Comment by astraldev** [comment]
change the division for the input and button to a form element so it submits the input then validiate it smth like that.

**Comment by Abbaskhurram255** [comment]
> change the division for the input and button to a form element so it submits the input then validiate it smth like that.

Say what?
