### ISSUE TITLE
Add isLeapYear function....

### ISSUE THREAD

**Issue by Abbaskhurram255** [Abbaskhurram255/abbaskhurram255.github.io#6]
Insert this between var username =... nd var msg:

/* function that lets user know whether its a leap year */
function isLeapYear(year) { return new Date(parseInt(year), 1, 29).getMonth() == 1; }

Note this tho: replace every # with current number. I mean yk I'm tryna say.

And this as a regexp:
q## = /(is|was)(year )? (this|\d{4})( a)? leap year/gi,

And this as an (else-if) condition:

if (q##.test(q)) {
   	$('#message').animate({height:'toggle', opacity: 'toggle'}, 800);
    
    msg = document.querySelector("#searchInput").value;
    msg = msg.replace(/this/gi, '2020');
    msg = msg.replace(/was/gi, 'is');
    msg = msg.substr(3, 4);
    msg = parseInt(msg);
    if (isLeapYear(msg)) {
    msg = `Of course, ${msg} is a leap year`;
    let x = msg.slice(11, 15);
    let curY = new Date().getFullYear();
    if (curY != x){ msg = msg.replace(/is/gi, 'was'); }
    } else {
    msg = "In accordance with my intelligence, no, it's not.";
    }
    $output.html(msg);
    console.log(msg);
    $('#message').delay(10000).animate({height:'toggle', opacity: 'toggle'}, 800);

**Comment by astraldev** [comment]
Use
```
function isLeapYear(year){
   if(year%4 == 0) return True
   else return False
}
```
All leap years are in 4's

**Comment by Abbaskhurram255** [comment]
> Use
> 
> ```
> function isLeapYear(year){
>    if(year%4 == 0) return True
>    else return False
> }
> ```
> 
> All leap years are in 4's

Quite simple, thanks!
